# Site settings
title:       Looking Cloudy
email:       brad@schulz.com
author:      Brad Schulz
description: "Interesting things"
baseurl:     ""
url:         "http://lookingcloudy.github.io"

# Google analytics
google_analytics: UA-65651364-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: lookingcloudy

# Social icons
github_username:
stackoverflow_id:
twitter_username: lookingcloudy
google_plus_id: 115619156177944092431
linkedin_username: bradschulz
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
